services:
  pandaiantrian_api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: pandaiantrian_api
    restart: always
    volumes:
      - .:/var/www
    networks:
      cloud-container:
        ipv4_address: 10.10.10.4

networks:
  cloud-container:
    external: true
