
services:
  pandaiantrian-api:
    build: .
    container_name: pandaiantrian-api
    restart: unless-stopped
    command: php artisan serve --host=0.0.0.0 --port=8000
    volumes:
      - .:/var/www
    networks:
      - cloud-container
    ports:
      - "8092:8000"
      # - "8088:8080"

  pandaiantrian-reverb:
    build: .
    container_name: pandaiantrian-reverb
    restart: unless-stopped
    command: php artisan reverb:start --host=0.0.0.0 --port=8080 --debug
    volumes:
      - .:/var/www
    networks:
      - cloud-container
    ports:
      - "8099:8080"

  pandaiantrian-queue:
    build: .
    container_name: pandaiantrian-queue
    restart: unless-stopped
    command: php artisan queue:work database --queue=default --tries=3 --backoff=10,30,60 --sleep=3 --timeout=120
    volumes:
      - .:/var/www
    networks:
      - cloud-container
    depends_on:
      - pandaiantrian-api

networks:
  cloud-container:
    external: true
