
services:
  pandaiantrian-api:
    build: .
    container_name: pandaiantrian-api
    restart: unless-stopped
    command: php artisan serve --host=0.0.0.0 --port=8000
    volumes:
      - .:/var/www
    networks:
      - cloud-container
    ports:
      - "8092:8000"
      # - "8088:8080"

  pandaiantrian-reverb:
    build: .
    container_name: pandaiantrian-reverb
    restart: unless-stopped
    command: php artisan reverb:start --host=0.0.0.0 --port=8080 --debug
    volumes:
      - .:/var/www
    networks:
      - cloud-container
    ports:
      - "8099:8080"
      
networks:
  cloud-container:
    external: true
