version: '3.8'

services:

  reverb:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: pandaiantrian-reverb
    restart: always
    command: bash -c "while [ ! -f vendor/autoload.php ]; do sleep 5; done; php artisan reverb:start --host=0.0.0.0 --port=8080"
    volumes:
      - .:/var/www
    networks:
      cloud-container:
        ipv4_address: 10.10.10.8

networks:
  cloud-container:
    external: true

